### ISSUE TITLE
Misalignment of pre-hash button and text with OMV 3.0.75.X+

### ISSUE THREAD

**Issue by fbearoff** [OpenMediaVault-Plugin-Developers/openmediavault-snapraid#10]
The new WebUI of OMV 3.0.75+ messes up the alignment of the pre-hash button and its associated text as shown in the attachment. This is rendered in Firefox 53.0.2 on Windows with default zoom.

![pre-hash text misalignment](https://cloud.githubusercontent.com/assets/11050285/26025173/84d3afd2-37af-11e7-9d11-0cb85853be03.png)

**Comment by ryecoaaron** [comment]
I will mention this to Volker since this is a core OMV issue.  I could move the checkbox (slider in 3.0.76) but I think it should be fixed in core OMV.

**Comment by ryecoaaron** [comment]
Decided to move it anyway.  Should be fixed in 3.6.8.
