### ISSUE TITLE
Wrong language when forced in OMV (French)

### ISSUE THREAD

**Issue by clexanis** [OpenMediaVault-Plugin-Developers/openmediavault-snapraid#16]
## Issue :

When the language is set to french, in the right menu of OMV after being connected, the plugin switch back to english.

I have also noted that this plugin have two folders in "/usr/share/openmediavault" (fr which is updated, and fr_FR which is not).

## Screenshots :

![firefox_2018-02-05_20-36-31](https://user-images.githubusercontent.com/29154441/35824961-c9199e30-0ab4-11e8-839b-e51accc676bd.png)
![firefox_2018-02-05_20-36-50](https://user-images.githubusercontent.com/29154441/35824970-cc62a14a-0ab4-11e8-848e-c6f074d55a62.png)

**Comment by ryecoaaron** [comment]
The fix has been pushed.  On your local system, just remove the /usr/share/openmediavault/locale/fr directory and clear your browser cache.
