### ISSUE TITLE
[snapraid-diff] WARNING! Ignoring special 'socket' file

### ISSUE THREAD

**Issue by henfri** [OpenMediaVault-Plugin-Developers/openmediavault-snapraid#18]
Hello,

/usr/sbin/omv-snapraid-diff
is giving me a message 
"WARNING! Ignoring special 'socket' file" for several files.
by Mail every time.

I think that messages should not be sent, if they are not important. This one is not.
I suggest to modify the omv-snapraid-diff script to ignore this warning.

One could make it more general by adding the option to the plugin to ignore all WARNINGs, but I am not sure this is a good idea.

Greetings,
Hendrik

**Comment by ryecoaaron** [comment]
The snapraid author recommend excluding the directories with special socket files in them which would remove this warning - https://sourceforge.net/p/snapraid/discussion/1677233/thread/43012b2f/

**Comment by henfri** [comment]
Thanks Aaron!
