### ISSUE TITLE
Only email on error, modification threshold

### ISSUE THREAD

**Issue by h45rd** [OpenMediaVault-Plugin-Developers/openmediavault-snapraid#20]
Hi,

Thanks for the nice snapraid implementation.

Would love the option to only receive mails on error and be able to set a modification threshold in addition to the delete threshold.
Any chance this would get merged if I take a stab at it?
If not I'd rather just write a simple script for my personal use.

Best,
h45rd

**Comment by ryecoaaron** [comment]
I'll merge it as long as it looks ok.
