### ISSUE TITLE
Scrub frequency issue

### ISSUE THREAD

**Issue by molnarti** [OpenMediaVault-Plugin-Developers/openmediavault-snapraid#22]
I thing the scrub frequency option does not work as it should. I have set my scrub frequency to 5 days, with the crob job running weekly, and it did not do any scrubbing for 3 weeks. 

I think that each running of snapraid resets the scrub cycle count regardless if an actual scrub was performed or not. so if I run `snapraid status`  it things there was a scrub run and does not run it with the weekly schedule. 

`

**Comment by ryecoaaron** [comment]
Closing due to age
