### ISSUE TITLE
Unnecessary volume selection when adding rules

### ISSUE THREAD

**Issue by auanasgheps** [OpenMediaVault-Plugin-Developers/openmediavault-snapraid#25]
Hi,

Volume selection is not needed when creating a rule, in fact rules will apply globally. 
![image](https://user-images.githubusercontent.com/20586878/79589293-79519300-80d5-11ea-888a-a13fdef7c67c.png)

The configuration adds comment showing the disk which was choosen, but does not have any effect at all.
```shell
[...]
exclude *.bak
exclude /snapraid.conf*

# Rule selected from /srv/fb4ab0da-2b79-4740-834a-7435c0123e28
exclude Thumbs.db
```

Please remove the entire disk selection from rule creation prompt as [it causes confusion](https://forum.openmediavault.org/index.php?thread/3004-howto-snapraid-in-omv/&postID=236248#post236248).

If it's there just to function as a comment or similar, please change the label.

**Comment by ryecoaaron** [comment]
Unfortunately, it cannot be removed.  The volume populates the rule's folder explorer.  And if I made the folder explorer a root folder explorer, then the plugin would have to figure out how to strip off the mount point since exclusions are not an absolute OS path.

**Comment by auanasgheps** [comment]
Well, you could either
- Remove the folder explorer and ask for manual addition (the relative path is okay)
- Add what you just told me as a comment

**Comment by ryecoaaron** [comment]
The plugin has been like this for almost 6 years.  I don't understand why it is so bad now?

If I don't know the mount point, it makes stripping off the mount point guess work.

**Comment by auanasgheps** [comment]
I was just reporting feedback from a user on the forum who was confused by this, as I was when I first added a rule some time ago.

**Comment by ryecoaaron** [comment]
I understand.  I have commented on the thread.  If someone reads the snapraid manual, the will see the filter has to be a relative path to snapraid volumes (yes, it is applied to them all).  There is no other way to show a directory tree that correctly displays the needed paths without choosing a volume.  I guess I could allow just typing a path in without selecting a volume but that is a lot of work to save a user half a second choosing the volume.  You could just pick the first volume and type in the path.  If it is was a root directory browser, it would take a lot longer and there would be risk that the plugin would strip off the wrong directory.  All that said, I really don't want to change something that has worked fine for so many years.

**Comment by auanasgheps** [comment]
Thanks for the explanation though.
