### ISSUE TITLE
ZFS filesystems (single drive zpools) not detected currently

### ISSUE THREAD

**Issue by ylluminate** [OpenMediaVault-Plugin-Developers/openmediavault-snapraid#29]
I decided that I wanted to take advantage of the additional compression provided by ZFS ZSTD[*] and the flexibility of ZFS working on so many different workstations in case of disaster, etc.  It sure beats all of the other options I've worked with including BTRFS and even EXT4 in terms of never having lost a bit of data from server/workstation crashes, etc.

From [SnapRAID's FAQ](https://www.snapraid.it/faq#fs), ZFS is one of the recommended filesystems for Data.

I've installed ZFS support via [OMV-Extras](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs), which [is supposed to be a first class filesystem plugin](https://openmediavault.readthedocs.io/en/5.x/administration/storage/filesystems.html) since it was developed "in conjunction with core of openmediavault."

The filesystems show up fine in "File Systems" in the GUI:
![filesystems](https://p153.p0.n0.cdn.getcloudapp.com/items/9ZuQl8GP/f41eee3a-fc44-476c-93bf-b71b83593de2.jpg?v=f2b4758f0748a7793c32a4aa3124dacc)

However, when I go to `SnapRAID` > `Drives` > `+ Add` and try to select a Drive, none of these show up:
![missing drives](https://p153.p0.n0.cdn.getcloudapp.com/items/kpunP7Yg/84ad86c2-4c07-4190-b742-121239c590bb.jpg?v=d0a8bc11beb12f6df2b40c649d458c92)

Also see [a short screencast](https://p153.p0.n0.cdn.getcloudapp.com/items/NQuYkJvg/1d54df12-dbe6-4801-9ef8-53fc137ec5d6.gif?v=9d3268f4f4c56f7b369ef37d1a1b621d).

**Comment by ryecoaaron** [comment]
Why are using snapraid with zfs?  zfs already does everything snapraid does.

The snapraid plugin is using a OMV function to populate that dropdown.  It is the same one that populates the drives in the Shared Folder creation dialog.
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-snapraid/blob/5.x/var/www/openmediavault/js/omv/module/admin/service/snapraid/Drives.js#L72

I guess I could look for another function but it won't be high on my priority list.

**Comment by ryecoaaron** [comment]
And zfs is only a partial recommend in the snapraid docs.

**Comment by ylluminate** [comment]
Compression and broad support (I have more systems that read ZFS than EXT*). 

Can I help you to add this? Otherwise, can you advise as to how I can manually edit the config to add these drives? (I suspect direct database changes to do this properly? I'm not seeing any config / diff file to insert these so far, but I'm not really familiar with how plugins alter configs for OMV yet, but I'm sure it's no problem with my background).

**Comment by ryecoaaron** [comment]
I understand why you are using zfs.  I don't know why you think you need snapraid if you are using zfs.

It would take me just as long to tell you how to help as it would to try and fix.  I have to see what enumerates the right list of disks for snapraid and if I can get the proper device in that list that snapraid config file needs.

**Comment by ylluminate** [comment]
I am *not* using raidz(1,2,3) here. I am using it simply as a basic filesystem and thus it won't cause any problems - I am interested in using flexible volume management/growth with MergeFS.

**Comment by ryecoaaron** [comment]
ok but it doesn't change my priority.  You are the first in 8+ years to use zfs with snapraid.  I was already starting to port this plugin to OMV 6.x and would like to focus on that.

**Comment by ylluminate** [comment]
I'll work on digging into the OMV source to find more out about `getCandidates` then and try to accelerate this since I'm on a deadline to get this in place today. Otherwise I'll figure out how config changes are made by this plugin (is this via database or a file/diff file of some sort on the OMV filesystems?) and manually change it if I can't help otherwise.

**Comment by ryecoaaron** [comment]
if you need it today, just change the snapraid.conf file manually and don't change anything in the plugin that will cause an "apply".

**Comment by ylluminate** [comment]
Ah, I had assumed that the warning existing in `/etc/snapraid.conf` meant that some automated updates might blow the file away, but it sounds like it won't ever actually modify `/etc/snapraid.conf` unless the SnapRAID GUI config changes are made AND applied. Sounds like I'm "safe" and could even perhaps set `/etc/snapraid.conf` read-only as a sanity saver.

Thanks for clarifying this.

**Comment by ryecoaaron** [comment]
read only won't do it.  you would have to set the immutable bit.

**Comment by ylluminate** [comment]
Right, `chattr +i /etc/snapraid.conf`, thanks.

**Comment by ylluminate** [comment]
As per in https://github.com/openmediavault/openmediavault/issues/1070 this is resolved for SnapRAID as well now.

Appreciate your input!
