### ISSUE TITLE
Allow custom placement of snapraid.content file

### ISSUE THREAD

**Issue by FlexibleToast** [OpenMediaVault-Plugin-Developers/openmediavault-snapraid#30]
Using SnapRAID with BTRFS, Snapper, and this script https://github.com/automorphism88/snapraid-btrfs solves the issue of parity integrity loss when a file is modified between syncs. The script creates a read only btrfs snapshot and does the parity sync based on that. The issue is that it requires the snapraid.content file to be located a different subvolume so it isn't included in the snapshot. It's trivially easy for me to create a subvol and move the snapraid.content file, but this plugin will overwrite the location. An option to choose a sub directory to place the snapraid.content file in would solve this issue.

**Comment by ryecoaaron** [comment]
So, you would want the content file for each drive in the same subfolder?  I'm thinking I could create an environment variable that could be overridden on the command line to allow this.  This would be a change made in the OMV 6.x version of the plugin since I'm not adding new features to 5.x verions.

**Comment by FlexibleToast** [comment]
Well, the same subfolder on each disk that is marked as a content drive. Right now I have it so each drive has a subvol named snapraid and that is where the content file lives. So something like `/srv/driveX/snapraid/snapraid.content`

Putting the feature on OMV6 only would be fine. The only thing holding me back from upgrading is that last I looked MergerFS and SnapRAID plugins weren't available for 6 yet.

**Comment by FlexibleToast** [comment]
In the jinja template I noticed it is currently: 

`content {{ drive.path }}/snapraid.content`

Changing it to something like

`content {{ drive path }}/{% if subfolder is defined %}{{ subfolder }}/{% endif %} snapraid.content`

I think that would add white spacing incorrectly, that's something I can never seem to remember and need to always play around with. If I understood how to change the UI elements and test it, I would submit the PR myself.

**Comment by ryecoaaron** [comment]
No worries.  I know exactly how to do it.  I don't want the selection in the web interface though.  That just makes it more complicated for other users (99.9% don't need it).  You would just have to run the omv-set command from the command line to set your override directory.  The snapraid plugin is almost done.  The mergerfs plugin is not.

**Comment by FlexibleToast** [comment]
As long as it's documented somewhere, that shouldn't be an issue. I'm sure this is an edge case, even if it makes by far the most sense to me. Bummer about the mergerfs plugin. Is there a way to be notified when it is ready? Literally the only things keeping me back from OMV6 right now.

**Comment by ryecoaaron** [comment]
You will just have to watch this page - https://forum.openmediavault.org/index.php?thread/39815-omv-extras-plugins-porting-progress-to-omv-6-x/ or the plugin tab on your OMV system.

OMV6 might be stable right now but it is alpha.  There may still be many changes coming.

**Comment by FlexibleToast** [comment]
Fair enough. I'm starting from a blank slate right now and it would have been nice to start fresh at 6. Thanks for the responses and I'll watch that page

**Comment by FlexibleToast** [comment]
A year later and I'm looking to upgrade to OMV6 as a fresh install. Is how to use the `omv-set` command documented somewhere? I can directly modify the snapraid.conf like I did for OMV5, but I would prefer to do it the "right" way.

**Comment by ryecoaaron** [comment]
Yes omv-env is [documented](https://docs.openmediavault.org/en/5.x/various/advset.html) but I never added any environment variables.  So, omv-env won't help with snapraid.

**Comment by FlexibleToast** [comment]
Oh, `omv-env`. I thought it was `omv-set` based on your previous comment. Bummer the variable isn't implemented yet, I'll have to do it the manual way for now I guess.

**Comment by ryecoaaron** [comment]
This feature has been added to 6.0.6 in the repo now.  Run the following to set the subfolder:

sudo omv-env set "OMV_SNAPRAID_CONTENT_SUBFOLDER" "test"
sudo omv-salt stage run prepare
