### ISSUE TITLE
Please update SnapRAID binary

### ISSUE THREAD

**Issue by auanasgheps** [OpenMediaVault-Plugin-Developers/openmediavault-snapraid#32]
Hello,
SnapRAID got updated to [version 12.0](https://github.com/amadvance/snapraid/blob/master/HISTORY), which has a new interesting feature: parallel disk scanning. It increaes SnapRAID speed when used with many drives.

Could you please update the binary to the version 12.0 in your repo?

Additionally, the current version installed by the plugin on OMV6 doesn't show the version and instead shows `vnone`
![image](https://user-images.githubusercontent.com/20586878/147711778-9d60e35b-04f7-40ac-bad1-a00edc6e4a1b.png)

On OMV5 does indeed:
![image](https://user-images.githubusercontent.com/20586878/147711839-5e4b144e-1771-4d42-bde5-8728dca17b73.png)

My script reads this value, that's why I noticed this small thing, but I'm not sure if it's related to the plugin or not.

**Comment by ryecoaaron** [comment]
I knew 12.0 had been released but I wanted to setup more automation around the build.  I just haven't had time to get to that.

As for the version string, all I do is build the source with debuild.  I really don't know why there would be no version.  Perhaps your script should get the version the way the plugin does? - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-snapraid/blob/master/usr/share/openmediavault/engined/rpc/snapraid.inc#L335  Otherwise, feel free to look into it and I will change my build script.

**Comment by auanasgheps** [comment]
> I knew 12.0 had been released but I wanted to setup more automation around the build. I just haven't had time to get to that.
> 
> As for the version string, all I do is build the source with debuild. I really don't know why there would be no version. Perhaps your script should get the version the way the plugin does? - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-snapraid/blob/master/usr/share/openmediavault/engined/rpc/snapraid.inc#L335 Otherwise, feel free to look into it and I will change my build script.

Thanks for the heads up, so your plugin gets reads the package version, not `snapraid -V output`. I will implement the change
So If you just build the source, I guess snapraid 11.5 and Debian 11 don't play well together!

**Comment by ryecoaaron** [comment]
https://omv-extras.org/testing/snapraid_12.0-1_amd64.deb

aaron@omv6dev:/srv/plugins/snapraid$ snapraid --version
snapraid v12.0 by Andrea Mazzoleni, http://www.snapraid.it

**Comment by auanasgheps** [comment]
Thanks for coming back so fast!
So I don't have to make changes :)

**Comment by ryecoaaron** [comment]
12.1 is in the testing repo.

**Comment by auanasgheps** [comment]
Good one, this time you were faster than my word!

**Comment by auanasgheps** [comment]
hey, I can see has been removed from the testing repo. Are you planning a public updated then?

**Comment by ryecoaaron** [comment]
testing repo not testing folder on omv-extras server.  You can enable the testing repo in omv-extras.

$ apt-cache policy snapraid
snapraid:
  Installed: 12.1
  Candidate: 12.1
  Version table:
 *** 12.1 500
        500 https://openmediavault-plugin-developers.github.io/packages/debian shaitan-testing/main amd64 Packages

**Comment by ryecoaaron** [comment]
I put 12.2 in the repo a couple of weeks ago.

**Comment by auanasgheps** [comment]
Thank you!
