### ISSUE TITLE
Support for multiple arrays.

### ISSUE THREAD

**Issue by thenebular** [OpenMediaVault-Plugin-Developers/openmediavault-snapraid#36]
Snapraid allows you to specify configuration files when running it, allowing you to have multiple separate arrays on one system. Multiple arrays can make better use of drives and space, when one is working with many drives of differing sizes. Case in point, I just recently acquired two 8tb drives which are the largest drives I have. With the number of drives I have, it's recommended I run dual parity. Because they are the largest drives, I would either need to put both as parity drives, or leave part of the drives unprotected. With two configuration files, I can have one array with the 8tb drives and a couple others in it, and another array with the rest of the drives.

I can do this from the command line, but I think it would be a good thing to have this option from the OMV gui.

**Comment by ryecoaaron** [comment]
I need to think about this one because it is a big change and won't be easy to migrate existing installs to the new config.  It also won't be used by many people.

**Comment by ryecoaaron** [comment]
6.2 in the testing repo now supports multiple arrays.

**Comment by d4g79** [comment]
Hi,

how come the plugin installed from OMV6 (6.2.1) has not installed the 1.1.3  script that this repo has??

Thanks

**Comment by ryecoaaron** [comment]
The current version of the plugin was released before I made the changes to the script.  I need to finish making changes.
