### ISSUE TITLE
Snapraid config file data disk naming

### ISSUE THREAD

**Issue by edemauro** [OpenMediaVault-Plugin-Developers/openmediavault-snapraid#37]
Noticed that the data disks are prefixed with "disk" instead of "data" in the config file (https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-snapraid/blob/master/srv/salt/omv/deploy/snapraid/files/etc-snapraid_conf.j2#L16). 

Looking at the documentation for Snapraid, shouldn't "disk" be "data"? I can't find "disk" in the documentation (https://www.snapraid.it/manual#7)

Here is the example config file provided in the snapraid repo showing the usage of the "data" prefix: https://github.com/amadvance/snapraid/blob/master/snapraid.conf.example

**Comment by ryecoaaron** [comment]
That particular code/config hasn't changed in a long time.  I will look at updating.  Are you seeing a problem?

**Comment by edemauro** [comment]
No I haven't. However, I've only recently installed the plugin within the past couple of days. I just want to make sure it works as expected.

**Comment by ryecoaaron** [comment]
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-snapraid/commit/15a19f8977650276f51e78771534c5fc61c7437e
