### ISSUE TITLE
Folder-based or Disk-based?

### ISSUE THREAD

**Issue by sulisu** [OpenMediaVault-Plugin-Developers/openmediavault-snapraid#38]
https://wiki.archlinux.org/title/SnapRAID

> [SnapRAID](https://www.snapraid.it/) is a folder-based backup tool that behaves like a software or hardware RAID5/6 disk raid, but is not a disk raid itself.

In the Web gui setting page of snapraid, when creating a new data or content disk, user can only select whole disk, not a specified path. It's not quite consistent with the concept of snapraid.

My use case: I have a disk with bad sector in the middle, so I fdisked it to two partitions leave the area with bad sectors untouched, mounted the two partition under a path ,and specified this path in snapraid config as a data disk.

I know that current web gui is straight-forward for new user to snapraid, it's not bad or wrong. Maybe specify a path  could be possibile with something like a advanced setting checkbox?

PS:
More thoughts on it making me realize its not so simple to change the disk selectioin droplist to a textbox. To handle my use case in a way consistent with OMV, snapraid plugin has to create and manage symlinks to make it working.  Since using snapraid under cli is not so difficult, it's may not worth the effort to make the web gui so advanced.

**Comment by ryecoaaron** [comment]
Not sure why you are quoting the Arch docs.  The [SnapRAID manual](https://www.snapraid.it/manual) is the source of truth.  The first line in the description of SnapRAID in the manual is:

**Comment by sulisu** [comment]
Just comment to make it clear.

In the official manual [https://www.snapraid.it/manual](https://www.snapraid.it/manual)

```
you have to create the configuration file /etc/snapraid.conf with the following options:

parity /mnt/diskp/snapraid.parity
content /var/snapraid/snapraid.content
content /mnt/disk1/snapraid.content
content /mnt/disk2/snapraid.content
data d1 /mnt/disk1/
data d2 /mnt/disk2/
data d3 /mnt/disk3/

```

"parity" and "data" is exactly pointed to a file path and folder path, not a disk device.

**Comment by ryecoaaron** [comment]
parity and content files have to point to a file path since they are files.  Yes, data is pointing to a folder path but it is meant to be the disk's mount point.  I understand snapraid can be made to work with folders but that is not what it is designed for.

If you want to split your disk, just create two partitions around your bad sectors.  You will be able to use each partition for data.  If there are things on those disks that you don't want to calculate parity on, create exclude rules.  There is no reason to use folders in the manner you describe.

**Comment by sulisu** [comment]
> If you want to split your disk, just create two partitions around your bad sectors. You will be able to use each partition for data. If there are things on those disks that you don't want to calculate parity on, create exclude rules. There is no reason to use folders in the manner you describe.

I think this solution, which assigning partitions on a physical harddisk to multiple "data disk"(by the definition of snapraid) is wrong and dangerous.

One "parity" disk can recover one 'data' disk failure, not One nT parity file can recover nT data regardless where they are, am I right? I can not find where the author has witten this explicitly, but how he talks about parity disk and data disk make me think so.

If I'm right, If partitions on one physical disk are assigned to different 'data' disks, when the one physical disk fails, two or more 'data' disks lost. In this situation, some data will be unrecoverable. So, the mount points of these partitions must be treated as folders in one parent folder,and then assign this parent folder to one "data" disk  by Snapraid.

**Comment by ryecoaaron** [comment]
Jeez, I was just giving you ideas for your situation.  This isn't a problem if you just use the plugin as designed.  But if you want to be able to handle two disks failing which losing two partitions would be the same as, then you need double parity.  I'm done here.

**Comment by ryecoaaron** [comment]
Please take this to the forum if you want to discuss further but I will not be participating.
