### ISSUE TITLE
Syslog option, creates rsyslog config file, but doesn't seem to log anything

### ISSUE THREAD

**Issue by psyciknz** [OpenMediaVault-Plugin-Developers/openmediavault-snapraid#39]
I've got logs coming to email.  But I have the syslog=true option turned on.
in rsyslog.d I can see:
```
:msg, contains, "omv-snapraid-diff[" /var/log/snapraid-diff.log
```
But this log is always empty.  And in teh Sync/scrub script in /usr/sbin/omv-snapraid there's no mention on syslog in there.   I expected to see something pushing the log entries to the defined syslog server.

Am I missing something?

**Comment by ryecoaaron** [comment]
The syslog setting only applies to the omv-snapraid-diff scrip.

**Comment by psyciknz** [comment]
> The syslog setting only applies to the omv-snapraid-diff scrip.

Which means what?  I can see it dumping that script run to /var/log/snapraid.log   Not sure how syslog fits in there.

**Comment by ryecoaaron** [comment]
Evidently the syslog function doesn't do anything anymore.  I didn't write and really don't maintain omv-snapraid-diff script.  And it looks like the log file changed which means the rsyslog entry doesn't do anything.  I really have no idea why someone would want to syslog it.  I will look at removing it.

**Comment by psyciknz** [comment]
Just to shove the contents of what is emailed to syslog.  Which in my case goes to Humio

**Comment by ryecoaaron** [comment]
Removed in 7.0.3 in repo now.
