### ISSUE TITLE
Unknown command 'sync --pre-hash' error when selecting pre-hash for nightly diff script in OMV snapraid settings

### ISSUE THREAD

**Issue by janstaunton** [OpenMediaVault-Plugin-Developers/openmediavault-snapraid#43]
Hello,

If I select pre-hash in the scheduled diff script settings, I get the error

`Unknown command 'sync --pre-hash'`

as an email and the sync doesn't run

The following patch to the diff script fixes this for me at least:

```diff
--- /usr/sbin/omv-snapraid-diff 2024-02-18 22:48:46.000000000 +0000
+++ omv-snapraid-diff.working   2024-02-09 20:32:24.654049491 +0000
@@ -389,7 +389,7 @@
 # set pre-hash option
 PREHASH_VALUE=$(omv_config_get "/config/services/snapraid/prehash")
 if [ $PREHASH_VALUE -eq 1 ]; then
-       prehash=" --pre-hash"
+       prehash="-h"
 else
        prehash=""
 fi
@@ -459,8 +459,8 @@
                echo "SnapRAID SYNC Job started - $(date)" >> $TMP_OUTPUT
                echo "----------------------------------------" >> $TMP_OUTPUT

-               # we should eventually grep %
-               $SNAPRAID_BIN --conf $SNAPRAID_CONF sync${prehash} >> $TMP_OUTPUT
+               # we should eventually grep
+               $SNAPRAID_BIN --conf $SNAPRAID_CONF sync ${prehash} >> $TMP_OUTPUT
                #wait for the job to finish
                wait
```

I'm not sure that changing prehash to -h is adding any value, but the second part of the diff is.  Suspecting that bash interprets the two bits as one arg and does the wrong thing.

Not sure of the wider implications of this otherwise would have submitted a PR!

**Comment by ryecoaaron** [comment]
-h and --pre-hash are the same.  There is no need to change them

>   -h, --pre-hash          Pre-hash all the new data

But this was "bug" already fixed.  It is caused by some systems not have the correct PATH set and they can't find the snapraid binary.  I hard-coded it in the fix.  This issue was tracking it - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-snapraid/issues/41

I assume you are still on OMV 6.x?

**Comment by janstaunton** [comment]
This is happening with openmediavault-snapraid (7.0.3) and openmediavault (7.0-32) on Debian 12.5

**Comment by ryecoaaron** [comment]
What is the output of:  dpkg -l | grep snapraid

**Comment by janstaunton** [comment]
```
❯ dpkg -l | grep snapraid
ii  openmediavault-snapraid             7.0.3                               all          snapraid plugin for OpenMediaVault.
ii  snapraid                            12.2-1                              amd64        backup program for disk arrays
```

**Comment by ryecoaaron** [comment]
I've never seen bash "see" something with a space in it as one command without double quotes around it.  I made a short test script to test different scenarios and all work.

```
#!/bin/bash

SNAPRAID_BIN="/usr/bin/snapraid"
# space in variable
prehash=" --pre-hash"
$SNAPRAID_BIN sync${prehash}
# space in command
prehash="--pre-hash"
$SNAPRAID_BIN sync ${prehash}
# space in variable with short flag
prehash=" -h"
$SNAPRAID_BIN sync${prehash}
# space in command with short flag
prehash="-h"
$SNAPRAID_BIN sync ${prehash}
# test variable with just space
prehash=" "
$SNAPRAID_BIN sync${prehash}
# test variable empty
prehash=""
$SNAPRAID_BIN sync ${prehash}
```

**Comment by janstaunton** [comment]
Could it be one of the shellchecks? At first glance they look unrelated

`# shellcheck disable=SC1090,SC1091,SC2086,SC2129,SC2162,SC2181,SC2219`

**Comment by janstaunton** [comment]
Same here, your script executes fine on the same box where the error occurs 🤷

**Comment by ryecoaaron** [comment]
Can you try this version of the script?  https://omv-extras.org/testing/omv-snapraid-diff

**Comment by janstaunton** [comment]
That version successfully did a diff and sync, I didn't explicitly test scrub but I can trigger that by altering my cycle count if you think that test is valuable

**Comment by ryecoaaron** [comment]
I don't think you need to test scrub since I changed it the same way.  I think I will just push these changes to the plugin.

**Comment by janstaunton** [comment]
7.0.4 works a treat, thank you for all the effort on this one!
