### ISSUE TITLE
Conflicting SLS IDs with borgbackup

### ISSUE THREAD

**Issue by sages** [OpenMediaVault-Plugin-Developers/openmediavault-snapraid#44]
Not sure that I'm down the correct rabbit hole however:
On an upgraded omv 6 to and a new omv 7 install with both snapraid and borgbackup plugins installed when running 'omv-salt stage deploy' I get the following error:
          ID: run_state_deploy
    Function: salt.state
      Result: False
     Comment: Run failed on minions: debian
     Started: 14:47:16.362779
    Duration: 9266.39 ms
     Changes:
              debian:
                  Data failed to compile:
              ----------
                  Detected conflicting IDs, SLS IDs need to be globally unique.
                  The conflicting ID is 'configure_borg_envvar_dir' and is found in SLS 'base:omv.deploy.borgbackup.default' and SLS 'base:omv.deploy.snapraid.default'

Summary for debian
------------
Succeeded: 1 (changed=1)
Failed:    1
------------
Total states run:     2
Total run time:  10.923 s
[ERROR   ] {'out': 'highstate', 'ret': {'debian': ["Detected conflicting IDs, SLS IDs need to be globally unique.\n    The conflicting ID is 'configure_borg_envvar_dir' and is found in SLS 'base:omv.deploy.borgbackup.default' and SLS 'base:omv.deploy.snapraid.default'"]}}

A quick look at /srv/salt/omv/deploy/snapraid/default.sls shows an entry for borgbackup which appears to coincide with the reported error.
Not sure why an entry for borgbackup default env var would be in the snapraid config
Rod

**Comment by ryecoaaron** [comment]
Thanks for pointing this out.  It was a typo.  This is fixed in the 7.0.5 version of the snapraid plugin in the repo now.
