### ISSUE TITLE
Cannot delete SnapRAID Arrays

### ISSUE THREAD

**Issue by auanasgheps** [OpenMediaVault-Plugin-Developers/openmediavault-snapraid#45]
Hi
I cannot delete SnapRAID Arrays:

![immagine](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-snapraid/assets/20586878/5c72030d-a4a4-4f26-9dac-196f4007faea)

This is what I get.
This either happens with newly generated arrays that never had a disk attached or arrays that had a disk before and I wanted to delete them.

OMV: 7.0-32
SnapRAID Plugin: 7.0.5

**Comment by ryecoaaron** [comment]
Fixed in 7.0.6 in the repo now.
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-snapraid/commit/01844bec0a9413faa4c4dbbb33b86e197e687be7

**Comment by auanasgheps** [comment]
Thanks for the support and the fast fix!
